name: project_boilerplate
description: "A Flutter project boilerplate."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.20.0 <3.33.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  easy_localization: ^3.0.7+1
  flutter_screenutil: ^5.9.3
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  flash: ^3.1.1
  dio: ^5.8.0+1
  flutter_svg: ^2.2.0
  flutter_svg_provider: ^1.0.7
  lottie: ^3.3.1
  shimmer: ^3.0.0
  introduction_screen: ^3.1.17
  cached_network_image: ^3.4.1
  croppy: ^1.3.6

  intl: ^0.19.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.4
#  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^16.0.0
  timezone: ^0.10.1
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.4.15
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4



flutter_gen:
  output: lib/generated/ # Optional: where generated files will be stored
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/fonts/
    - assets/translations/
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/placeholder_logo.png"
  image_path: "assets/images/placeholder_logo.png"
  web:
    generate: true
    image_path: "assets/images/waslny_logo.png"
    background_color: "#000000"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/waslny_logo_under12.png
  image_dark: assets/images/waslny_logo_under12.png
  fullscreen: true
  android_gravity: center

  android_12:
    image: assets/images/waslny_logo.png
    image_dark: assets/images/waslny_logo.png
    color: "#ffffff"
    color_dark: "#000000"
    android_gravity: center
  android: true
  ios: true
  web: false
#  web:false
#    color: "#1E1E1E"

package_rename_config:
  android:
    app_name: "App Name"
    package_name: "com.AppName.app"

  ios:
    app_name: "App Name"
    bundle_name: "App Name"
    package_name: "com.AppName.app"